/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  SessionDtoOfGuid
} from '../../../../libs/sdk/models';
import type {
  EmailSignInRequest,
  EmailSignUpRequest,
  SessionDtoOfGuidOutput
} from '../../../../libs/sdk/models';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable()
export class IdentityService {
  private readonly http = inject(HttpClient);
/**
 * Sign in a user using their email credentials
 * @summary Email sign in
 */
 postApiIdentitySignInEmail(emailSignInRequest: EmailSignInRequest, options?: HttpClientBodyOptions): Observable<SessionDtoOfGuidOutput>;
 postApiIdentitySignInEmail(emailSignInRequest: EmailSignInRequest, options?: HttpClientEventOptions): Observable<HttpEvent<SessionDtoOfGuidOutput>>;
 postApiIdentitySignInEmail(emailSignInRequest: EmailSignInRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<SessionDtoOfGuidOutput>>;
  postApiIdentitySignInEmail(
    emailSignInRequest: EmailSignInRequest, options?: HttpClientObserveOptions): Observable<SessionDtoOfGuidOutput | HttpEvent<SessionDtoOfGuidOutput> | AngularHttpResponse<SessionDtoOfGuidOutput>> {
    if (options?.observe === 'events') {
      return this.http.post<SessionDtoOfGuidOutput>(
      `/api/identity/sign-in/email`,
      emailSignInRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: SessionDtoOfGuid.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<SessionDtoOfGuidOutput>(
      `/api/identity/sign-in/email`,
      emailSignInRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: SessionDtoOfGuid.parse(response.body) })));
    }

    return this.http.post<SessionDtoOfGuidOutput>(
      `/api/identity/sign-in/email`,
      emailSignInRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => SessionDtoOfGuid.parse(data)));
  }
/**
 * Create a new user account using email
 * @summary Email sign up
 */
 postApiIdentitySignUpEmail<TData = void>(emailSignUpRequest: EmailSignUpRequest, options?: HttpClientBodyOptions): Observable<TData>;
 postApiIdentitySignUpEmail<TData = void>(emailSignUpRequest: EmailSignUpRequest, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 postApiIdentitySignUpEmail<TData = void>(emailSignUpRequest: EmailSignUpRequest, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  postApiIdentitySignUpEmail<TData = void>(
    emailSignUpRequest: EmailSignUpRequest, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/identity/sign-up/email`,
      emailSignUpRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/identity/sign-up/email`,
      emailSignUpRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/identity/sign-up/email`,
      emailSignUpRequest,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type PostApiIdentitySignInEmailClientResult = NonNullable<SessionDtoOfGuidOutput>
export type PostApiIdentitySignUpEmailClientResult = NonNullable<void>
