/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const ActivateOrganizationHeaders = zod.object({
  "x-api-version": zod.string().optional()
})

export type ActivateOrganizationHeaders = zod.input<typeof ActivateOrganizationHeaders>;
export type ActivateOrganizationHeadersOutput = zod.output<typeof ActivateOrganizationHeaders>;
