/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const ActivateOrganizationParams = zod.object({
  "api-version": zod.string().optional()
})

export type ActivateOrganizationParams = zod.input<typeof ActivateOrganizationParams>;
export type ActivateOrganizationParamsOutput = zod.output<typeof ActivateOrganizationParams>;
