/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const AnonymousTypeOfboolean = zod.object({
  "ok": zod.boolean()
})

export type AnonymousTypeOfboolean = zod.input<typeof AnonymousTypeOfboolean>;
export type AnonymousTypeOfbooleanOutput = zod.output<typeof AnonymousTypeOfboolean>;
