/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const AvailabilityResponse = zod.object({
  "available": zod.boolean()
})

export type AvailabilityResponse = zod.input<typeof AvailabilityResponse>;
export type AvailabilityResponseOutput = zod.output<typeof AvailabilityResponse>;
