/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const ContactDtoOfGuid = zod.object({
  "verified": zod.boolean().optional(),
  "verifiedAt": zod.iso.datetime({"offset":true}).nullish(),
  "type": zod.string(),
  "value": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})

export type ContactDtoOfGuid = zod.input<typeof ContactDtoOfGuid>;
export type ContactDtoOfGuidOutput = zod.output<typeof ContactDtoOfGuid>;
