/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const emailSignUpBodyPasswordMin = 8;


export const EmailSignUpBody = zod.object({
  "email": zod.string(),
  "password": zod.string().min(emailSignUpBodyPasswordMin),
  "confirmPassword": zod.string().nullable()
})

export type EmailSignUpBody = zod.input<typeof EmailSignUpBody>;
export type EmailSignUpBodyOutput = zod.output<typeof EmailSignUpBody>;
