/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const emailSignUpRequestPasswordMin = 8;


export const EmailSignUpRequest = zod.object({
  "email": zod.string(),
  "password": zod.string().min(emailSignUpRequestPasswordMin),
  "confirmPassword": zod.string().nullable()
})

export type EmailSignUpRequest = zod.input<typeof EmailSignUpRequest>;
export type EmailSignUpRequestOutput = zod.output<typeof EmailSignUpRequest>;
