/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const EmailSignUpHeaders = zod.object({
  "x-api-version": zod.string().optional()
})

export type EmailSignUpHeaders = zod.input<typeof EmailSignUpHeaders>;
export type EmailSignUpHeadersOutput = zod.output<typeof EmailSignUpHeaders>;
