/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const emailSignInRequestStaySignedInDefault = false;
export const EmailSignInRequest = zod.object({
  "email": zod.string().nullish(),
  "password": zod.string().nullish(),
  "staySignedIn": zod.boolean().default(emailSignInRequestStaySignedInDefault)
})

export type EmailSignInRequest = zod.input<typeof EmailSignInRequest>;
export type EmailSignInRequestOutput = zod.output<typeof EmailSignInRequest>;
