/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const emailSignInBodyStaySignedInDefault = false;
export const EmailSignInBody = zod.object({
  "email": zod.string().nullish(),
  "password": zod.string().nullish(),
  "staySignedIn": zod.boolean().default(emailSignInBodyStaySignedInDefault)
})

export type EmailSignInBody = zod.input<typeof EmailSignInBody>;
export type EmailSignInBodyOutput = zod.output<typeof EmailSignInBody>;
