/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const EmailSignInParams = zod.object({
  "api-version": zod.string().optional()
})

export type EmailSignInParams = zod.input<typeof EmailSignInParams>;
export type EmailSignInParamsOutput = zod.output<typeof EmailSignInParams>;
