/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const errorMessagePayloadStatusRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');

export const ErrorMessagePayload = zod.object({
  "message": zod.string().nullish(),
  "status": zod.union([zod.number(),zod.stringFormat('int32', errorMessagePayloadStatusRegExpTwo)]).optional()
})

export type ErrorMessagePayload = zod.input<typeof ErrorMessagePayload>;
export type ErrorMessagePayloadOutput = zod.output<typeof ErrorMessagePayload>;
