/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const GetAntiforgeryTokenHeaders = zod.object({
  "x-api-version": zod.string().optional()
})

export type GetAntiforgeryTokenHeaders = zod.input<typeof GetAntiforgeryTokenHeaders>;
export type GetAntiforgeryTokenHeadersOutput = zod.output<typeof GetAntiforgeryTokenHeaders>;
