/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const GetSessionParams = zod.object({
  "api-version": zod.string().optional()
})

export type GetSessionParams = zod.input<typeof GetSessionParams>;
export type GetSessionParamsOutput = zod.output<typeof GetSessionParams>;
