/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const GetSessionHeaders = zod.object({
  "x-api-version": zod.string().optional()
})

export type GetSessionHeaders = zod.input<typeof GetSessionHeaders>;
export type GetSessionHeadersOutput = zod.output<typeof GetSessionHeaders>;
