/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const HealthResponseDto = zod.object({
  "ok": zod.boolean().optional()
})

export type HealthResponseDto = zod.input<typeof HealthResponseDto>;
export type HealthResponseDtoOutput = zod.output<typeof HealthResponseDto>;
