/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const IsNameAvailableParams = zod.object({
  "name": zod.string().optional(),
  "api-version": zod.string().optional()
})

export type IsNameAvailableParams = zod.input<typeof IsNameAvailableParams>;
export type IsNameAvailableParamsOutput = zod.output<typeof IsNameAvailableParams>;
