/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const lookupProjectsParamsLimitDefault = `10`;
export const LookupProjectsParams = zod.object({
  "limit": zod.string().default(lookupProjectsParamsLimitDefault),
  "api-version": zod.string().optional()
})

export type LookupProjectsParams = zod.input<typeof LookupProjectsParams>;
export type LookupProjectsParamsOutput = zod.output<typeof LookupProjectsParams>;
