/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const OrganizationLookupOfGuid = zod.object({
  "name": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})

export type OrganizationLookupOfGuid = zod.input<typeof OrganizationLookupOfGuid>;
export type OrganizationLookupOfGuidOutput = zod.output<typeof OrganizationLookupOfGuid>;
