/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const postApiIdentitySignInEmailBodyStaySignedInDefault = false;
export const PostApiIdentitySignInEmailBody = zod.object({
  "email": zod.string(),
  "password": zod.string(),
  "staySignedIn": zod.boolean().default(postApiIdentitySignInEmailBodyStaySignedInDefault)
})

export type PostApiIdentitySignInEmailBody = zod.input<typeof PostApiIdentitySignInEmailBody>;
export type PostApiIdentitySignInEmailBodyOutput = zod.output<typeof PostApiIdentitySignInEmailBody>;
