/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const postApiIdentitySignUpEmailBodyPasswordMin = 8;


export const PostApiIdentitySignUpEmailBody = zod.object({
  "email": zod.string(),
  "password": zod.string().min(postApiIdentitySignUpEmailBodyPasswordMin),
  "confirmPassword": zod.string().nullable(),
  "firstName": zod.string().nullish(),
  "lastName": zod.string()
})

export type PostApiIdentitySignUpEmailBody = zod.input<typeof PostApiIdentitySignUpEmailBody>;
export type PostApiIdentitySignUpEmailBodyOutput = zod.output<typeof PostApiIdentitySignUpEmailBody>;
