/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const ProjectLookupOfGuid = zod.object({
  "name": zod.string().nullish(),
  "icon": zod.string().nullish(),
  "isArchived": zod.boolean().optional(),
  "description": zod.string().nullish(),
  "organizationId": zod.uuid().optional(),
  "createdBy": zod.uuid().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})

export type ProjectLookupOfGuid = zod.input<typeof ProjectLookupOfGuid>;
export type ProjectLookupOfGuidOutput = zod.output<typeof ProjectLookupOfGuid>;
