/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const SessionDtoOfGuid = zod.object({
  "ip": zod.string().optional(),
  "accountId": zod.uuid().optional(),
  "activeOrganizationId": zod.uuid().optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})

export type SessionDtoOfGuid = zod.input<typeof SessionDtoOfGuid>;
export type SessionDtoOfGuidOutput = zod.output<typeof SessionDtoOfGuid>;
