/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const UserDtoOfGuid = zod.object({
  "firstName": zod.string().nullish(),
  "photo": zod.string().nullish(),
  "isBanned": zod.boolean().optional(),
  "isOnboarded": zod.boolean().optional(),
  "banReason": zod.string().nullish(),
  "contacts": zod.array(zod.object({
  "verified": zod.boolean().optional(),
  "verifiedAt": zod.iso.datetime({"offset":true}).nullish(),
  "type": zod.string(),
  "value": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})).optional(),
  "lastName": zod.string().nullish(),
  "fullName": zod.string().nullish(),
  "initials": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "id": zod.uuid()
})

export type UserDtoOfGuid = zod.input<typeof UserDtoOfGuid>;
export type UserDtoOfGuidOutput = zod.output<typeof UserDtoOfGuid>;
