/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  SessionDtoOfGuid
} from '../../../../libs/sdk/models';
import type {
  EmailSignInParams,
  EmailSignInRequest,
  EmailSignUpParams,
  EmailSignUpRequest,
  GetAntiforgeryTokenParams,
  GetSessionParams,
  SessionDtoOfGuidOutput,
  SignOutParams
} from '../../../../libs/sdk/models';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable()
export class AuthService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get current user's session
 */
 getSession(params?: GetSessionParams, options?: HttpClientBodyOptions): Observable<SessionDtoOfGuidOutput>;
 getSession(params?: GetSessionParams, options?: HttpClientEventOptions): Observable<HttpEvent<SessionDtoOfGuidOutput>>;
 getSession(params?: GetSessionParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<SessionDtoOfGuidOutput>>;
  getSession(
    params?: GetSessionParams, options?: HttpClientObserveOptions): Observable<SessionDtoOfGuidOutput | HttpEvent<SessionDtoOfGuidOutput> | AngularHttpResponse<SessionDtoOfGuidOutput>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<SessionDtoOfGuidOutput>(
      `/api/auth/session`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: SessionDtoOfGuid.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<SessionDtoOfGuidOutput>(
      `/api/auth/session`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: SessionDtoOfGuid.parse(response.body) })));
    }

    return this.http.get<SessionDtoOfGuidOutput>(
      `/api/auth/session`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => SessionDtoOfGuid.parse(data)));
  }
/**
 * @summary Sign out
 */
 signOut<TData = void>(params?: SignOutParams, options?: HttpClientBodyOptions): Observable<TData>;
 signOut<TData = void>(params?: SignOutParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 signOut<TData = void>(params?: SignOutParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  signOut<TData = void>(
    params?: SignOutParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/sign-out`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/sign-out`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.post<TData>(
      `/api/auth/sign-out`,undefined,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Generate a new anti-forgery token for the current session
 * @summary Obtain antiforgery token
 */
 getAntiforgeryToken<TData = void>(params?: GetAntiforgeryTokenParams, options?: HttpClientBodyOptions): Observable<TData>;
 getAntiforgeryToken<TData = void>(params?: GetAntiforgeryTokenParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getAntiforgeryToken<TData = void>(params?: GetAntiforgeryTokenParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getAntiforgeryToken<TData = void>(
    params?: GetAntiforgeryTokenParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/aif-token`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/aif-token`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.get<TData>(
      `/api/auth/aif-token`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
/**
 * Sign in a user using their email credentials
 * @summary Email sign in
 */
 emailSignIn(emailSignInRequest: EmailSignInRequest,
    params?: EmailSignInParams, options?: HttpClientBodyOptions): Observable<SessionDtoOfGuidOutput>;
 emailSignIn(emailSignInRequest: EmailSignInRequest,
    params?: EmailSignInParams, options?: HttpClientEventOptions): Observable<HttpEvent<SessionDtoOfGuidOutput>>;
 emailSignIn(emailSignInRequest: EmailSignInRequest,
    params?: EmailSignInParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<SessionDtoOfGuidOutput>>;
  emailSignIn(
    emailSignInRequest: EmailSignInRequest,
    params?: EmailSignInParams, options?: HttpClientObserveOptions): Observable<SessionDtoOfGuidOutput | HttpEvent<SessionDtoOfGuidOutput> | AngularHttpResponse<SessionDtoOfGuidOutput>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<SessionDtoOfGuidOutput>(
      `/api/auth/sign-in/email`,
      emailSignInRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: SessionDtoOfGuid.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<SessionDtoOfGuidOutput>(
      `/api/auth/sign-in/email`,
      emailSignInRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: SessionDtoOfGuid.parse(response.body) })));
    }

    return this.http.post<SessionDtoOfGuidOutput>(
      `/api/auth/sign-in/email`,
      emailSignInRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => SessionDtoOfGuid.parse(data)));
  }
/**
 * Create a new user account using email
 * @summary Email sign up
 */
 emailSignUp<TData = unknown>(emailSignUpRequest: EmailSignUpRequest,
    params?: EmailSignUpParams, options?: HttpClientBodyOptions): Observable<TData>;
 emailSignUp<TData = unknown>(emailSignUpRequest: EmailSignUpRequest,
    params?: EmailSignUpParams, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 emailSignUp<TData = unknown>(emailSignUpRequest: EmailSignUpRequest,
    params?: EmailSignUpParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  emailSignUp<TData = unknown>(
    emailSignUpRequest: EmailSignUpRequest,
    params?: EmailSignUpParams, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/auth/sign-up/email`,
      emailSignUpRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/auth/sign-up/email`,
      emailSignUpRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    );
    }

    return this.http.post<TData>(
      `/api/auth/sign-up/email`,
      emailSignUpRequest,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    );
  }
};

export type GetSessionClientResult = NonNullable<SessionDtoOfGuidOutput>
export type SignOutClientResult = NonNullable<void>
export type GetAntiforgeryTokenClientResult = NonNullable<void>
export type EmailSignInClientResult = NonNullable<SessionDtoOfGuidOutput>
export type EmailSignUpClientResult = NonNullable<unknown>
