#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^src/app/.*\.(ts|html)$')

if [-n "$STAGED_FILES"]; then
  echo "Detected changes in Angular templates or coponents. Running translate.ps1..."
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File ./translate.ps1
  if [$? -ne 0]; then
    echo "Error: Translate script failed. Commit aborted."
    exit 1
  fi
  echo "Staging updated translation file..."
  git add src/locales/*.xlf
fi

exit 0
