/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DataMount.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpContext,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import {
  UserDtoOfGuid
} from '../../../../libs/sdk/models';
import type {
  GetMeParams,
  UserDtoOfGuidOutput
} from '../../../../libs/sdk/models';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
): Record<string, AngularHttpParamValueWithNullable> {
  const filteredParams: Record<string, AngularHttpParamValueWithNullable> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}



export type GetMeAccept = typeof GetMeAccept[keyof typeof GetMeAccept];

export const GetMeAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

@Injectable()
export class UserService {
  private readonly http = inject(HttpClient);
/**
 * @summary Get current user information
 */
 getMe(accept: 'text/plain',
    params?: GetMeParams, options?: HttpClientOptions): Observable<string>;
  getMe(accept: 'application/json',
    params?: GetMeParams, options?: HttpClientOptions): Observable<UserDtoOfGuidOutput>;
  getMe(accept: 'text/json',
    params?: GetMeParams, options?: HttpClientOptions): Observable<UserDtoOfGuidOutput>;
  getMe(accept?: GetMeAccept,
    params?: GetMeParams, options?: HttpClientOptions): Observable<UserDtoOfGuidOutput | string>;
  getMe(
    accept: GetMeAccept = 'application/json',
    params?: GetMeParams,
    options?: HttpClientOptions
  ): Observable<UserDtoOfGuidOutput | string> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<UserDtoOfGuidOutput>(`/api/users/me`, {
        ...options,
        responseType: 'json',
        headers,
        params: filteredParams,
      }).pipe(map(data => UserDtoOfGuid.parse(data)));
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/users/me`, {
        ...options,
        responseType: 'text',
        headers,
        params: filteredParams,
      }) as Observable<string>;
    }

    return this.http.get<UserDtoOfGuidOutput>(`/api/users/me`, {
      ...options,
      responseType: 'json',
      headers,
      params: filteredParams,
    }).pipe(map(data => UserDtoOfGuid.parse(data)));
  }
};

